Repository planetarium/9c-headless-metric-gql-aggregator, pull requests merged in 2023-02, with the labels that each got.

#8 fix: Upgrade https
  app.py
Labels: Extra Small

#9 Revert "fix: Upgrade https"
  app.py
Labels: Extra Small

#7 update node list
  app.py
Labels: Small

#10 reduce timeout in post requests
  app.py
Labels: Extra Small

#11 add block interval and tx count metrics
  app.py
  poetry.lock
  pyproject.toml
Labels: Large
